name: Deploy Vite Static Site

on:
  push:
    branches:
      - main # Runs when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Allow pushing to gh-pages

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Update the base path dynamically in vite.config.ts
      - name: Update base path in vite.config.ts
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          sed -i 's|base: \"/\"|base: \"/'${REPO_NAME}'/\"|' vite.config.ts
          cat vite.config.ts  # To check if the config was updated correctly

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }} # Use the default GitHub token
