name: Deploy Vite Static Site

on:
  push:
    branches:
      - main # Runs when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Allow pushing to gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Update base path in vite.config.js
        run: |
          # Ensure the working directory is the root of the repository
          cd $GITHUB_WORKSPACE  # Make sure we're in the correct directory

          # Extract the repository name from the GITHUB_REPOSITORY variable
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)

          # Check if vite.config.js exists in the root directory
          if [ -f "vite.config.js" ]; then
            echo "vite.config.js found, updating base path"
            sed -i "s|base: \"/\"|base: \"/$REPO_NAME/\"|" vite.config.js
          else
            echo "vite.config.js not found in the root directory"
            exit 1
          fi

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }} # Use the default GitHub token
